//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using UnityEngine;

namespace Common {
	/**
	 * Contains GameObject extensions
	 */
	public static class GameObjectExtensions {
		/**
		 * Queries for a component
		 * Throws assertion error if component is not found
		 */
		public static T GetRequiredComponent<T>(this GameObject self) where T : Component {
			T component = self.GetComponent<T>();
			Assertion.NotNull(component);
			return component;
		}
		
		public static Option<T> GetComponentAsOption<T>(this GameObject self) where T : Component {
			T component = self.GetComponent<T>();
			return component == null ? Option<T>.NONE : Option<T>.Some(component);
		}
		
		/**
		 * Deactivates the GameObject
		 */
		public static void Deactivate(this GameObject self) {
			self.SetActive(false);
		}
		
		/**
		 * Activates the GameObject
		 */
		public static void Activate(this GameObject self) {
			self.SetActive(true);
		}
	}
}

