//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using UnityEngine;
using UnityEngine.UI;

namespace Common {
	public static class SliderExtensions {

		/**
		 * Sets the extents of a slider
		 * This is the safe way to set the extents
		 */
		public static void SetValueExtents(this Slider slider, float min, float max) {
			Assertion.IsTrue(min.TolerantLesserThanOrEquals(max));

			// ensure that maxValue is really higher than minValue first
			// I speculate that when you set a maxValue that is lesser than the current minValue (also the other way around), Unity blows up (I don't know why)
			// Or it only happens when it is bound to uFrame
			slider.maxValue = float.MaxValue;
			slider.minValue = float.MinValue;
			
			slider.minValue = min;
			slider.maxValue = max;
		}

	}
}
